# Generated by Django 3.1.7 on 2021-02-26 10:33

from django.db import migrations, models
import payment_gateway.utils.string
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date Created')),
            ],
        ),
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('value', models.CharField(default=payment_gateway.utils.string.random_string_gen, max_length=5, verbose_name='OTP Value')),
                ('expiry', models.PositiveSmallIntegerField(default=5, verbose_name='Expiry in Minutes')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date Created')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('external_id', models.CharField(max_length=100, verbose_name='External ID')),
                ('currency', models.CharField(default='GHC', max_length=5, verbose_name='Currency')),
                ('amount', models.DecimalField(decimal_places=2, default=5.0, max_digits=100, verbose_name='Amount')),
                ('customer_name', models.CharField(max_length=250, verbose_name='Customer ID')),
                ('customer_email', models.EmailField(max_length=250, verbose_name='Customer Email')),
                ('customer_mobile', models.CharField(max_length=10, verbose_name='Customer Mobile')),
                ('description', models.CharField(max_length=500, verbose_name='Transaction Description')),
                ('payment_method', models.CharField(max_length=10, verbose_name='Payment Method')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date Created')),
            ],
        ),
    ]
